@extends('planning.layout')
@section('planning-content')
<h2 class="font-semibold">{{ ['board'=>'Board dashboard · CMT reports','cmt'=>'CMT dashboard · Department reports','department'=>'Department dashboard'][$level] }}</h2>
<form method="GET" action="{{ route('planning.overview') }}" class="kcard p-4 flex flex-wrap gap-3 items-end">
@if(count($dashboardLevels)>1)<div><label>Dashboard</label><select name="dashboard">@foreach($dashboardLevels as $key=>$label)<option value="{{ $key }}" @selected($level===$key)>{{ $label }}</option>@endforeach</select></div>@else<input type="hidden" name="dashboard" value="{{ $level }}">@endif<div><label>Semester</label><select name="period_id"><option value="">All semesters</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(request('period_id')===$period->id)>{{ $period->name }}</option>@endforeach</select></div>@if($level==='department')<div><label>Department</label><select name="department_id">@foreach($departments as $department)<option value="{{ $department->id }}" @selected($departmentId===$department->id)>{{ $department->name }}</option>@endforeach</select></div>@endif<button class="btn-primary">Apply filters</button></form>
<div class="grid md:grid-cols-4 gap-3">@foreach(['documents'=>'Approved goal documents','goals'=>'Key results','reported'=>'Results with reported progress','overdue'=>'Overdue results below target'] as $key=>$label)<div class="kcard p-4"><p class="text-xs text-gray-500">{{ $label }}</p><p class="text-2xl font-semibold">{{ $summary[$key] }}</p></div>@endforeach</div>
@if($tasks!==null)<div class="kcard p-4 flex flex-wrap gap-6 text-sm"><strong>Department work</strong>@foreach(['todo'=>'To do','in_progress'=>'In progress','review'=>'Review','done'=>'Done'] as $key=>$label)<span>{{ $label }}: {{ $tasks[$key]??0 }}</span>@endforeach</div>@endif
<div class="kcard overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Goal / key result</th><th>Department / semester</th><th>Owner</th><th>Target</th><th>Reported actual</th><th>Due</th></tr></thead><tbody>@forelse($goals as $goal)<tr><td><strong>{{ $goal->details['objective']??'' }}</strong><p>{{ $goal->title }}</p><div class="text-xs">@if(auth()->user()->can('planning.'.$goal->document->type.'_view'))<a href="{{ route('planning.show',$goal->document) }}">{{ $goal->document->title }} →</a>@else{{ $goal->document->title }}@endif</div></td><td>{{ $goal->document->department?->name??'CMT' }}<div class="text-xs text-gray-500">{{ $goal->document->period?->name }}</div></td><td>{{ $goal->owner?->name??'Unassigned' }}</td><td>{{ $goal->target }} {{ $goal->metric }}</td><td>{{ $goal->actual??'Not reported' }}</td><td>{{ $goal->due_on }}<div class="text-xs text-gray-500">{{ \App\Services\Planning\Dates::bs($goal->due_on) }}</div></td></tr>@empty<tr><td colspan="6" class="text-gray-500">No approved {{ $level==='board'?'CMT':'Department' }} goals for this selection. Reports will appear after goals are approved.</td></tr>@endforelse</tbody></table><div class="p-3">{{ $goals->links() }}</div></div>
@endsection
