@extends('planning.layout')
@section('planning-content')
<div class="kcard p-5 space-y-3"><div class="flex justify-between gap-3"><h2 class="font-semibold text-lg">{{ $document->title }}</h2><span>{{ ucwords(str_replace('_',' ',$document->status)) }}</span></div><p class="text-sm text-gray-500">{{ $document->department?->name ?? 'College' }} · {{ $document->period?->name }} · Revision {{ $document->revision }}</p>@if($document->type==='cmt_goals')<details><summary class="text-teal-700">Semester theme and milestones</summary><p class="whitespace-pre-line">{{ $document->description }}</p></details>@else<p class="whitespace-pre-line">{{ $document->description }}</p>@endif
@if($document->status==='approved' && $document->type!=='strategy')@can('planning.'.$document->type.'_create')<form method="POST" action="{{ route('planning.amend',$document) }}">@csrf<button class="text-teal-700">Create amendment</button></form>@endcan @endif
@if($document->parent)<p class="text-sm">Linked to: <a href="{{ route('planning.show',$document->parent) }}">{{ $document->parent->title }}</a></p>@endif
@if(in_array($document->status,['draft','returned']))@if(\App\Services\Planning\Governance::canWrite(auth()->user(),$document->type,$document->type==='strategy'?'edit':'create'))<a href="{{ route('planning.edit',$document) }}">Edit draft</a>@endif @if(\App\Services\Planning\Governance::canWrite(auth()->user(),$document->type,'submit'))<form method="POST" action="{{ route('planning.action',$document) }}">@csrf<input type="hidden" name="version" value="{{ $document->version }}"><button class="btn-primary" name="action" value="submit">Submit for approval</button></form>@endif @endif
@if(in_array($document->status,['pending_verification','pending_approval']))<p class="text-sm">Awaiting {{ $document->step()['name']??'' }}</p>@if(auth()->user()->isSuperAdmin() || ($document->step()['user_id']??null)===auth()->id())
@if(auth()->user()->isSuperAdmin() && ($document->step()['user_id']??null)!==auth()->id())<p class="text-sm text-teal-700">You can perform this step as Super Admin. Your action will be recorded in the approval history.</p>@endif<form method="POST" action="{{ route('planning.action',$document) }}" class="space-y-3">@csrf<input type="hidden" name="version" value="{{ $document->version }}"><textarea name="note" placeholder="Decision note (required when returning or rejecting)"></textarea><div class="flex gap-3"><button name="action" value="accept" class="btn-primary">{{ $document->status==='pending_verification'?'Verify':'Approve' }}</button><button name="action" value="return" class="btn-secondary">Return</button><button name="action" value="reject" class="text-red-600">Reject</button></div></form>@endif @endif
</div>
@if($document->type==='strategy')
@include('planning.strategy-matrix')
@include('planning.strategy-review')
@elseif($document->type==='cmt_goals')
@include('planning.cmt-table')
@else
<div class="kcard overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Item</th><th>Owner / due date</th><th>{{ $document->type==='budget'?'Allocation':'Target / budget' }}</th><th>Definition of Done</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td class="max-w-md">{{ $item->title }}<div class="text-xs text-gray-500 whitespace-pre-line">{{ $item->description }}</div><div class="text-xs text-gray-500">{{ $item->programme }} {{ $item->batch }}</div>@foreach(($item->details??[]) as $field=>$value)@if(is_string($value) && $value!=='')<div class="text-xs">{{ ucwords(str_replace('_',' ',$field)) }}: {{ $value }}</div>@endif @endforeach </td><td>{{ $item->owner?->name ?? $document->creator?->name }}<div class="text-xs">{{ $item->due_on }} <span class="text-xs text-gray-500">{{ \App\Services\Planning\Dates::bs($item->due_on) }}</span></div></td><td>@if($document->type==='budget')Rs {{ number_format($item->amount,2) }}@if(isset($publications[$item->id]))<div class="text-xs text-teal-700">Published to Department Budgets</div>@can('activity_forms.create')<a href="{{ route('activity-forms.create',['budget_id'=>$publications[$item->id]]) }}">Create Activity Form →</a>@endcan @endif @else {{ $item->target }} {{ $item->metric }} @if($item->requires_budget)<div class="text-xs">Budget required</div>@endif @endif
@if(in_array($document->type,['cmt_goals','goals']) && $document->status==='approved')<p>Actual: {{ $item->actual ?? 'No check-in' }}</p>@if(\App\Services\Planning\Governance::canWrite(auth()->user(),$document->type,'report') && ($item->owner_id===auth()->id() || $document->created_by===auth()->id() || auth()->user()->isSuperAdmin()))<details><summary>Record progress</summary><form method="POST" action="{{ route('planning.checkin',[$document,$item]) }}">@csrf<input type="number" step="0.01" min="0" name="actual" required placeholder="Current value"><textarea name="evidence" required placeholder="Evidence / measurement"></textarea><button class="btn-primary">Save check-in</button></form></details>@endif @endif</td><td class="max-w-sm whitespace-pre-line">{{ $item->definition_of_done }}</td></tr>@endforeach</tbody></table></div>
@endif
@if($document->type!=='strategy' && in_array($document->status,['draft','returned']))@can('planning.'.$document->type.'_create')<details class="kcard p-4"><summary>Import items from Excel / CSV</summary><a href="{{ route('planning.import.template') }}">Download template</a><form class="space-y-3 mt-3" method="POST" enctype="multipart/form-data" action="{{ route('planning.import.preview',$document) }}">@csrf<input type="file" name="file" accept=".xlsx,.csv" required><input name="sheet" placeholder="Sheet name (optional; defaults to first sheet)"><button class="btn-primary">Preview import</button></form></details>@endcan @endif
<details class="kcard p-4"><summary>Approval history</summary>@forelse($document->decisions as $decision)<p class="text-sm py-2">{{ $decision->created_at }} · {{ $decision->actor?->name }} · {{ ucfirst($decision->decision) }}<span class="block text-gray-500">{{ $decision->note }}</span></p>@empty<p class="py-2 text-sm">No decisions yet.</p>@endforelse</details>
@endsection
