@extends('planning.layout')
@section('planning-content')
<div class="kcard p-5 space-y-3"><div class="flex justify-between gap-3"><h2 class="font-semibold text-lg">{{ $document->title }}</h2><span>{{ ucwords(str_replace('_',' ',$document->status)) }}</span></div><p class="text-sm text-gray-500">{{ $document->department?->name ?? 'College' }} · {{ $document->period?->name }} · Revision {{ $document->revision }}</p><p class="whitespace-pre-line">{{ $document->description }}</p>
@if($document->parent)<p class="text-sm">Linked to: <a href="{{ route('planning.show',$document->parent) }}">{{ $document->parent->title }}</a></p>@endif
@if(in_array($document->status,['draft','returned']))@can('planning.'.$document->type.'_create')<a href="{{ route('planning.edit',$document) }}">Edit draft</a>@endcan @can('planning.'.$document->type.'_submit')<form method="POST" action="{{ route('planning.action',$document) }}">@csrf<input type="hidden" name="version" value="{{ $document->version }}"><button class="btn-primary" name="action" value="submit">Submit for approval</button></form>@endcan @endif
@if(in_array($document->status,['pending_verification','pending_approval']))<p class="text-sm">Awaiting {{ $document->step()['name']??'' }}</p>@if(($document->step()['user_id']??null)===auth()->id())<form method="POST" action="{{ route('planning.action',$document) }}" class="space-y-3">@csrf<input type="hidden" name="version" value="{{ $document->version }}"><textarea name="note" placeholder="Decision note (required when returning or rejecting)"></textarea><div class="flex gap-3"><button name="action" value="accept" class="btn-primary">{{ $document->status==='pending_verification'?'Verify':'Approve' }}</button><button name="action" value="return" class="btn-secondary">Return</button><button name="action" value="reject" class="text-red-600">Reject</button></div></form>@endif @endif
</div>
<div class="kcard overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Item</th><th>Owner / due date</th><th>{{ $document->type==='budget'?'Allocation':'Target / budget' }}</th><th>Definition of Done</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td class="max-w-md">{{ $item->title }}<div class="text-xs text-gray-500 whitespace-pre-line">{{ $item->description }}</div></td><td>{{ $item->owner?->name ?? $document->creator?->name }}<div class="text-xs">{{ $item->due_on }}</div></td><td>@if($document->type==='budget')Rs {{ number_format($item->amount,2) }}@if(isset($publications[$item->id]))<div class="text-xs text-teal-700">Published to Department Budgets</div>@endif @else {{ $item->target }} {{ $item->metric }} @if($item->requires_budget)<div class="text-xs">Budget required</div>@endif @endif</td><td class="max-w-sm whitespace-pre-line">{{ $item->definition_of_done }}</td></tr>@endforeach</tbody></table></div>
<details class="kcard p-4"><summary>Approval history</summary>@forelse($document->decisions as $decision)<p class="text-sm py-2">{{ $decision->created_at }} · {{ $decision->actor?->name }} · {{ ucfirst($decision->decision) }}<span class="block text-gray-500">{{ $decision->note }}</span></p>@empty<p class="py-2 text-sm">No decisions yet.</p>@endforelse</details>
@endsection
