@extends('planning.layout')
@section('planning-content')
<div class="flex gap-4 text-sm">@foreach(['board'=>'Board','backlog'=>'Backlog & sprints','calendar'=>'My calendar'] as $key=>$label)<a href="{{ route('planning.tasks',['mode'=>$key]) }}">{{ $label }}</a>@endforeach</div>
<form class="kcard p-3 flex gap-3"><input type="hidden" name="mode" value="{{ $mode }}"><input name="search" placeholder="Find a task" value="{{ request('search') }}">@if($mode==='calendar')<input type="month" name="month" value="{{ $month }}">@else<select name="sprint"><option value="">All sprints / backlog</option>@foreach($sprints as $s)<option value="{{ $s->id }}" @selected(request('sprint')===$s->id)>{{ $s->name }}</option>@endforeach</select>@endif<button class="btn-primary">Apply</button></form>
<details class="kcard p-4"><summary>+ Add task</summary><form class="grid md:grid-cols-3 gap-3 mt-3" method="POST" action="{{ route('planning.tasks.store') }}">@csrf<div><label>Title *</label><input name="title" required></div><div><label>Assignee *</label><select name="assignee_id">@foreach($users as $u)<option value="{{ $u->id }}" @selected($u->id===auth()->id())>{{ $u->name }}</option>@endforeach</select></div><div><label>Department</label><select name="department_id"><option value="">Personal</option>@foreach($departments as $d)<option value="{{ $d->id }}">{{ $d->name }}</option>@endforeach</select></div><div><label>Parent task (optional)</label><select name="parent_id"><option value="">Standalone task</option>@foreach($tasks->whereNull('parent_id') as $parent)<option value="{{ $parent->id }}">{{ $parent->title }}</option>@endforeach</select></div><div><label>Reviewer</label><select name="reviewer_id"><option value="">Task creator</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div><div><label>Due date (AD)</label><input type="date" name="due_on"></div><div><label>Priority</label><select name="priority"><option>normal</option><option>high</option><option>low</option></select></div><div><label>Description</label><textarea name="description"></textarea></div><div><label>Definition of Done</label><textarea name="definition_of_done"></textarea></div><div><label><input type="checkbox" name="is_private" value="1" checked> Private personal task</label><button class="btn-primary">Create task</button></div></form></details>
@if($mode==='backlog')@can('planning.tasks')<details class="kcard p-4"><summary>Manage sprints</summary><form method="POST" action="{{ route('planning.sprints.store') }}" class="grid md:grid-cols-3 gap-3 mt-3">@csrf<div><label>Sprint name</label><input name="name" required></div><div><label>Goal</label><input name="goal" required></div><div><label>Department</label><select name="department_id" required>@foreach($departments as $d)<option value="{{ $d->id }}">{{ $d->name }}</option>@endforeach</select></div><div><label>Start</label><input type="date" name="starts_on" required></div><div><label>End</label><input type="date" name="ends_on" required></div><button class="btn-primary">Create sprint</button></form>@foreach($sprints as $s)<div class="flex justify-between py-3 border-b"><span>{{ $s->name }} · {{ $s->starts_on }} — {{ $s->ends_on }} · {{ $s->status }}</span>@if($s->status!=='completed')<form method="POST" action="{{ route('planning.sprints.action',$s) }}">@csrf<button class="text-teal-700" name="action" value="{{ $s->status==='planned'?'start':'complete' }}">{{ $s->status==='planned'?'Start sprint':'Complete sprint' }}</button></form>@endif</div>@endforeach</details>@endcan @endif
@if($mode==='calendar')
@php $first=\Carbon\Carbon::parse($month.'-01');$days=$first->daysInMonth; @endphp
<div class="kcard p-4 overflow-x-auto"><h3 class="font-semibold mb-3">{{ $first->format('F Y') }}</h3><div class="grid grid-cols-7 min-w-[700px] gap-2">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day)<div class="text-xs text-gray-500">{{ $day }}</div>@endforeach @for($i=1;$i<$first->dayOfWeekIso;$i++)<div></div>@endfor @for($day=1;$day<=$days;$day++)@php $date=$first->copy()->day($day)->format('Y-m-d'); @endphp<div class="border rounded p-2 min-h-[100px]"><span class="text-xs">{{ $day }}</span>@foreach($tasks->where('due_on',$date) as $task)<div class="mt-2 text-xs rounded bg-teal-50 p-2">{{ $task->title }}<span class="block text-gray-500">{{ str_replace('_',' ',$task->status) }}</span></div>@endforeach</div>@endfor</div></div>
@else
<div class="grid grid-cols-1 {{ $mode==='board'?'lg:grid-cols-4':'lg:grid-cols-2' }} gap-4">
@foreach(($mode==='board'?['todo'=>'To Do','in_progress'=>'In Progress','review'=>'Review','done'=>'Done']:['all'=>'Tasks']) as $status=>$label)<section data-status="{{ $status }}" class="bg-gray-100 rounded-lg p-3 space-y-3"><h3 class="text-sm font-semibold">{{ $label }}</h3>@forelse(($status==='all'?$tasks:$tasks->where('status',$status)) as $task)<article class="task-card" draggable="true" data-task="{{ $task->id }}"><h4 class="font-medium text-sm">{{ $task->title }}</h4><p class="text-xs text-gray-500 mt-2">{{ $task->assignee?->name }} · {{ $task->due_on ?? 'No due date' }} <span class="text-xs text-gray-500">{{ \App\Services\Planning\Dates::bs($task->due_on) }}</span> {{ $task->is_private?'· Private':'' }}</p>@if($task->blocked_reason)<p class="text-xs text-amber-700">Blocked: {{ $task->blocked_reason }}</p>@endif<details class="mt-3 text-sm"><summary>Details / update</summary><p class="whitespace-pre-line py-2">{{ $task->description }}</p><p class="text-xs whitespace-pre-line">Definition of Done: {{ $task->definition_of_done ?: 'Not specified' }}</p><form class="space-y-2 mt-3" method="POST" action="{{ route('planning.tasks.update',$task) }}">@csrf @method('PUT')<input type="hidden" name="version" value="{{ $task->version }}"><label>Status</label><select name="status">@foreach(['todo'=>'To Do','in_progress'=>'In Progress','review'=>'Review','done'=>'Done'] as $value=>$text)<option value="{{ $value }}" @selected($task->status===$value)>{{ $text }}</option>@endforeach</select><label>Sprint</label><select name="sprint_id"><option value="">Backlog</option>@foreach($sprints->where('department_id',$task->department_id)->where('status','!=','completed') as $s)<option value="{{ $s->id }}" @selected($task->sprint_id===$s->id)>{{ $s->name }}</option>@endforeach</select><label>Task due date (AD)</label><input type="date" name="due_on" value="{{ $task->due_on }}"><label>Completion evidence</label><textarea name="evidence">{{ $task->evidence }}</textarea><label>Blocked reason</label><input name="blocked_reason" value="{{ $task->blocked_reason }}"><label>Note / reopening reason</label><textarea name="note"></textarea><button class="btn-primary">Save</button></form></details></article>@empty<p class="text-sm text-gray-500">No tasks.</p>@endforelse</section>@endforeach</div>
@endif
{{ $tasks->links() }}
<script>
document.addEventListener('DOMContentLoaded',()=>{let selected=null;document.querySelectorAll('[data-task]').forEach(card=>card.addEventListener('dragstart',event=>{selected=card;event.dataTransfer.setData('text/plain',card.dataset.task);}));document.querySelectorAll('section[data-status]').forEach(column=>{column.addEventListener('dragover',event=>event.preventDefault());column.addEventListener('drop',event=>{event.preventDefault();if(!selected||column.dataset.status==='all')return;let form=selected.querySelector('form');form.querySelector('[name=status]').value=column.dataset.status;selected.querySelector('details').open=true;form.requestSubmit();});});});
</script>
@endsection
