<?php $__env->startSection('title', $purchaseOrder->po_number); ?>

<?php $__env->startSection('content'); ?>
<?php
    $invoiceRows = $purchaseOrder->items->map(function ($item) {
        $invoiced = $item->invoicedQuantity();
        return ['item' => $item, 'remaining' => max(0, (float) $item->quantity - $invoiced), 'invoiced' => $invoiced];
    });
?>
<div class="space-y-6">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><a href="<?php echo e(route('vendor.portal.orders.index')); ?>" class="text-sm font-semibold text-teal-700 hover:text-teal-800">← Purchase orders</a><p class="mt-4 text-xs font-semibold uppercase tracking-wider text-slate-500">Purchase order</p><h1 class="mt-1 font-mono text-2xl font-bold text-slate-900"><?php echo e($purchaseOrder->po_number); ?></h1></div><a href="<?php echo e(route('vendor.portal.orders.pdf', $purchaseOrder)); ?>" class="btn-secondary">Download PDF</a></div>

    <section class="rounded-xl border border-slate-200 bg-white p-5"><dl class="grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Status</dt><dd class="mt-2"><span class="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-semibold text-blue-800"><?php echo e($purchaseOrder->statusLabel()); ?></span></dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Issued</dt><dd class="mt-2 font-medium"><?php echo e($purchaseOrder->created_at?->format('d M Y')); ?></dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Expected delivery</dt><dd class="mt-2 font-medium"><?php echo e($purchaseOrder->expected_delivery_date?->format('d M Y') ?? '—'); ?></dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">RFQ reference</dt><dd class="mt-2 font-mono font-medium"><?php echo e($purchaseOrder->rfqQuote?->rfq?->rfq_number ?? 'Standalone PO'); ?></dd></div></dl></section>

    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-900">Approved purchase order</h2><p class="mt-1 text-sm text-slate-500">Rates are fixed. Invoices may be submitted over multiple dates, up to the remaining approved quantity.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Item</th><th class="px-5 py-3">Unit</th><th class="px-5 py-3 text-right">Approved</th><th class="px-5 py-3 text-right">Invoiced</th><th class="px-5 py-3 text-right">Remaining</th><th class="px-5 py-3 text-right">Unit rate</th></tr></thead><tbody class="divide-y divide-slate-100"><?php $__currentLoopData = $invoiceRows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="px-5 py-4"><p class="font-medium text-slate-900"><?php echo e($row['item']->description); ?></p><?php if($row['item']->request_remarks): ?><p class="mt-1 text-xs text-slate-500"><?php echo e($row['item']->request_remarks); ?></p><?php endif; ?></td><td class="px-5 py-4 text-slate-600"><?php echo e($row['item']->unit); ?></td><td class="px-5 py-4 text-right font-mono"><?php echo e(number_format($row['item']->quantity, 3)); ?></td><td class="px-5 py-4 text-right font-mono"><?php echo e(number_format($row['invoiced'], 3)); ?></td><td class="px-5 py-4 text-right font-mono font-semibold <?php echo e($row['remaining'] > 0 ? 'text-amber-700' : 'text-green-700'); ?>"><?php echo e(number_format($row['remaining'], 3)); ?></td><td class="px-5 py-4 text-right font-mono">Rs <?php echo e(number_format($row['item']->unit_rate, 2)); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div></section>

    <section class="grid gap-5 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><div><h2 class="font-bold text-slate-900">Delivery address</h2><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600"><?php echo e($purchaseOrder->delivery_address); ?></p></div><div><h2 class="font-bold text-slate-900">Terms &amp; conditions</h2><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600"><?php echo e($purchaseOrder->terms_and_conditions); ?></p></div></section>

    <?php if(! $purchaseOrder->allItemsInvoiced()): ?>
    <section class="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><div class="mb-5"><p class="text-xs font-semibold uppercase tracking-wide text-teal-700">Invoice details</p><h2 class="mt-1 text-xl font-bold text-slate-900">Create invoice</h2><p class="mt-1 text-sm text-slate-500">Enter the quantity for this invoice. Each line amount and the invoice total are calculated automatically.</p></div>
        <?php if($errors->any()): ?><div class="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-800"><ul class="list-inside list-disc"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
        <form method="POST" action="<?php echo e(route('vendor.portal.orders.bills.store', $purchaseOrder)); ?>" enctype="multipart/form-data" class="space-y-5"><?php echo csrf_field(); ?>
            <div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-semibold text-slate-700">Bill / invoice number <span class="text-red-600">*</span><input name="bill_number" value="<?php echo e(old('bill_number')); ?>" required maxlength="100" class="mt-1.5 block w-full rounded-lg border-slate-300 text-sm shadow-sm focus:border-teal-500 focus:ring-teal-500"></label><label class="block text-sm font-semibold text-slate-700">Bill date <span class="text-red-600">*</span><input type="date" name="bill_date" value="<?php echo e(old('bill_date', now()->toDateString())); ?>" required class="mt-1.5 block w-full rounded-lg border-slate-300 text-sm shadow-sm focus:border-teal-500 focus:ring-teal-500"></label></div>
            <div class="overflow-hidden rounded-xl border border-slate-200"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Invoice item</th><th class="px-4 py-3 text-right">Remaining</th><th class="px-4 py-3 text-right">Approved rate</th><th class="px-4 py-3 text-right">This invoice qty</th><th class="px-4 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-slate-100"><?php $__currentLoopData = $invoiceRows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="px-4 py-4"><p class="font-semibold text-slate-900"><?php echo e($row['item']->description); ?></p><input type="hidden" name="items[<?php echo e($row['item']->id); ?>][item_id]" value="<?php echo e($row['item']->id); ?>"></td><td class="px-4 py-4 text-right font-mono"><?php echo e(number_format($row['remaining'], 3)); ?> <?php echo e($row['item']->unit); ?></td><td class="px-4 py-4 text-right font-mono">Rs <?php echo e(number_format($row['item']->unit_rate, 2)); ?></td><td class="px-4 py-4"><input type="number" inputmode="decimal" name="items[<?php echo e($row['item']->id); ?>][quantity]" value="<?php echo e(old('items.'.$row['item']->id.'.quantity')); ?>" min="0" max="<?php echo e($row['remaining']); ?>" step="0.001" placeholder="0" <?php echo e($row['remaining'] <= 0 ? 'disabled' : ''); ?> data-invoice-qty data-rate="<?php echo e($row['item']->unit_rate); ?>" data-line-target="invoice-line-<?php echo e($row['item']->id); ?>" class="w-full rounded-lg border border-teal-300 px-3 py-2 text-right font-mono font-bold focus:border-teal-500 focus:ring-teal-100"></td><td id="invoice-line-<?php echo e($row['item']->id); ?>" class="px-4 py-4 text-right font-mono font-bold text-teal-900">Rs 0.00</td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div>
            <div class="ml-auto max-w-md rounded-lg border border-teal-100 bg-teal-50 p-4 text-sm"><div class="flex justify-between py-1"><span>Invoice amount</span><span id="invoice-subtotal" class="font-mono font-semibold">Rs 0.00</span></div><div class="flex justify-between py-1"><span>Tax</span><span id="invoice-tax" class="font-mono font-semibold">Rs 0.00</span></div><div class="mt-2 flex justify-between border-t border-teal-200 pt-3 text-base font-bold text-teal-950"><span>Invoice total</span><span id="invoice-total" class="font-mono">Rs 0.00</span></div></div>
            <label class="block text-sm font-semibold text-slate-700">Manual bill file <span class="text-red-600">*</span><input type="file" name="bill_file" accept=".pdf,.jpg,.jpeg,.png,.heic,.heif" capture="environment" required class="mt-1.5 block w-full rounded-lg border border-slate-300 bg-white p-2 text-sm file:mr-4 file:rounded-md file:border-0 file:bg-teal-50 file:px-3 file:py-1.5 file:font-semibold file:text-teal-800"><span class="mt-1 block text-xs font-normal text-slate-500">Formats: PDF, JPG, PNG, HEIC · Max 20 MB</span></label><label class="block text-sm font-semibold text-slate-700">Notes / payment reference<textarea name="notes" rows="3" class="mt-1.5 block w-full rounded-lg border-slate-300 text-sm shadow-sm focus:border-teal-500 focus:ring-teal-500"><?php echo e(old('notes')); ?></textarea></label><div class="flex justify-end border-t border-slate-100 pt-5"><button class="inline-flex items-center justify-center rounded-lg bg-teal-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2">Submit invoice</button></div>
        </form>
    </section>
    <?php else: ?> <section class="rounded-xl border border-green-200 bg-green-50 p-5"><h2 class="font-bold text-green-900">All PO items invoiced</h2><p class="mt-1 text-sm text-green-800">Every approved quantity has been submitted through invoices.</p></section><?php endif; ?>
</div>
<script>
document.addEventListener('DOMContentLoaded', () => { const inputs = document.querySelectorAll('[data-invoice-qty]'); const taxRate = Number(<?php echo json_encode($purchaseOrder->tax_applied ? $purchaseOrder->tax_rate : 0, 15, 512) ?>) || 0; const money = value => `Rs ${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; const recalculate = () => { let subtotal = 0; inputs.forEach(input => { const total = (Number(input.value) || 0) * (Number(input.dataset.rate) || 0); subtotal += total; document.getElementById(input.dataset.lineTarget).textContent = money(total); }); const tax = subtotal * taxRate / 100; document.getElementById('invoice-subtotal').textContent = money(subtotal); document.getElementById('invoice-tax').textContent = money(tax); document.getElementById('invoice-total').textContent = money(subtotal + tax); }; inputs.forEach(input => input.addEventListener('input', recalculate)); recalculate(); });
</script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.vendor-portal', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ashbinkumarchamrel/Downloads/kathford-process/resources/views/vendor-portal/purchase-order.blade.php ENDPATH**/ ?>