<?php $__env->startSection('title', 'Quotation Requests'); ?>
<?php $__env->startSection('content'); ?>
<div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-wider text-teal-700">Quotation requests</p><h1 class="mt-1 text-2xl font-bold text-slate-900">RFQ history</h1><p class="mt-1 text-sm text-slate-500">Submit quotes, respond to negotiations, and follow awards.</p></div><div class="flex gap-1 rounded-lg bg-slate-100 p-1 text-xs font-semibold"><a href="<?php echo e(route('vendor.portal.quotes.index')); ?>" class="rounded-md px-3 py-2 <?php echo e($filter === 'all' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'); ?>">All</a><a href="<?php echo e(route('vendor.portal.quotes.index', ['filter' => 'action'])); ?>" class="rounded-md px-3 py-2 <?php echo e($filter === 'action' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'); ?>">Action</a><a href="<?php echo e(route('vendor.portal.quotes.index', ['filter' => 'review'])); ?>" class="rounded-md px-3 py-2 <?php echo e($filter === 'review' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'); ?>">Under review</a><a href="<?php echo e(route('vendor.portal.quotes.index', ['filter' => 'awarded'])); ?>" class="rounded-md px-3 py-2 <?php echo e($filter === 'awarded' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'); ?>">Awarded</a></div></div>
<section class="mt-6 divide-y divide-slate-100 overflow-hidden rounded-xl border border-slate-200 bg-white"><?php $__empty_1 = true; $__currentLoopData = $displayQuotes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $quote): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php
    $negotiation = $quote->items->contains(fn ($item) => $item->negotiation_message && !in_array($item->award_status, ['accepted', 'rejected'], true));
    $awarded = $quote->items->where('award_status', 'accepted')->count();
    $statusLabel = $negotiation ? 'Negotiation requested' : $quote->vendorStatusLabel();
    $statusClass = $negotiation ? 'bg-orange-100 text-orange-800' : ($awarded ? 'bg-emerald-100 text-emerald-800' : ($quote->status === 'invited' ? 'bg-amber-100 text-amber-800' : 'bg-blue-100 text-blue-800'));
?><div class="flex flex-col gap-4 px-5 py-5 sm:px-6 lg:flex-row lg:items-center lg:justify-between"><div><div class="flex flex-wrap items-center gap-2"><p class="font-mono text-xs font-bold text-slate-600"><?php echo e($quote->rfq->rfq_number); ?></p><span class="rounded-full px-2.5 py-1 text-xs font-semibold <?php echo e($statusClass); ?>"><?php echo e($statusLabel); ?></span></div><p class="mt-2 font-semibold text-slate-900"><?php echo e($quote->rfq->title); ?></p><p class="mt-1 text-sm text-slate-500"><?php echo e($quote->items->count()); ?> item<?php echo e($quote->items->count() === 1 ? '' : 's'); ?> · Deadline <?php echo e($quote->rfq->deadline?->format('d M Y') ?? 'Open'); ?></p></div><div class="flex items-center justify-between gap-5"><p class="font-mono text-sm font-semibold text-slate-700"><?php echo e($quote->status === 'invited' ? 'Not quoted' : 'Rs '.number_format((float) $quote->grand_total, 2)); ?></p><a href="<?php echo e(route('vendor.portal.quotes.show', $quote)); ?>" class="text-sm font-semibold text-teal-700"><?php echo e($negotiation ? 'Respond' : ($quote->status === 'invited' ? 'Submit quote' : 'View')); ?> →</a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="px-6 py-14 text-center text-sm text-slate-500">No quotation requests match this view.</div><?php endif; ?></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.vendor-portal', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ashbinkumarchamrel/Downloads/kathford-process/resources/views/vendor-portal/quotes.blade.php ENDPATH**/ ?>