<?php $__env->startSection('title', 'Supplier workspace'); ?>
<?php $__env->startSection('content'); ?>
<?php $__currentLoopData = \App\Models\ProcurementReturn::where('vendor_id',$vendor->id)->whereHas('checklist')->with('checklist.vendorBill')->latest()->get(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $return): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<section class="mb-4 rounded-xl border border-red-200 bg-red-50 p-5"><h2 class="font-semibold text-red-800">Invoice returned · <?php echo e($return->checklist->vendorBill->bill_number); ?></h2><p class="mt-2 text-sm text-red-900"><?php echo e($return->reason); ?></p><p class="mt-2 text-xs text-red-700"><?php echo e($return->created_at->format('d M Y H:i')); ?> · Please submit corrected goods/invoice through the purchase order.</p></section>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<h1 class="text-xl font-semibold text-slate-900">Welcome back, <?php echo e($vendor->name); ?></h1>
<section class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><a href="<?php echo e(route('vendor.portal.orders.index', ['filter' => 'open'])); ?>" class="rounded-xl border border-amber-200 bg-white p-5 transition hover:border-amber-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Purchase orders</p><p class="mt-3 text-3xl font-bold text-slate-900"><?php echo e($poSummary['pending']); ?></p><p class="mt-1 text-xs text-slate-500">Open orders needing an invoice</p></a><a href="<?php echo e(route('vendor.portal.quotes.index', ['filter' => 'action'])); ?>" class="rounded-xl border border-amber-200 bg-white p-5 transition hover:border-amber-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Quotation requests</p><p class="mt-3 text-3xl font-bold text-slate-900"><?php echo e($summary['action_required']); ?></p><p class="mt-1 text-xs text-slate-500">Quotes or negotiations requiring action</p></a><a href="<?php echo e(route('vendor.portal.payments.index')); ?>" class="rounded-xl border border-blue-200 bg-white p-5 transition hover:border-blue-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Payments</p><p class="mt-3 text-3xl font-bold text-slate-900"><?php echo e($payments->count()); ?></p><p class="mt-1 text-xs text-slate-500">Scheduled and authorised updates</p></a><a href="<?php echo e(route('vendor.portal.statement')); ?>" class="rounded-xl border border-teal-200 bg-white p-5 transition hover:border-teal-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Account statement</p><p class="mt-3 text-lg font-bold text-teal-800">View ledger →</p><p class="mt-1 text-xs text-slate-500">Invoices, settlements, and balance</p></a></section>
<?php if($actionRequired->isNotEmpty()): ?><section class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-5"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold text-slate-900">Needs attention</h2><p class="mt-1 text-sm text-slate-600">You have <?php echo e($actionRequired->count()); ?> quotation request<?php echo e($actionRequired->count() === 1 ? '' : 's'); ?> to review.</p></div><a href="<?php echo e(route('vendor.portal.quotes.index', ['filter' => 'action'])); ?>" class="rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-teal-700">Review requests</a></div></section><?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.vendor-portal', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ashbinkumarchamrel/Downloads/kathford-process/resources/views/vendor-portal/dashboard.blade.php ENDPATH**/ ?>