<?php $__env->startSection('title', 'Checklist '.$checklist->purchaseOrder?->po_number); ?>
<?php $__env->startSection('page-title', 'Procurement Checklist'); ?>

<?php $__env->startSection('content'); ?>
<?php $__currentLoopData = $checklist->returns; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $return): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="bg-red-50 border border-red-200 rounded-xl p-4 mb-4 text-sm"><strong>Returned to vendor · <?php echo e($return->created_at->format('d M Y H:i')); ?></strong><p><?php echo e($return->reason); ?></p></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('checklists.complete')): ?>
<?php if($checklist->status!=='returned'): ?><details class="kcard p-5 mb-4"><summary class="font-semibold text-red-700 cursor-pointer">Return goods or invoice to vendor</summary><form method="POST" action="<?php echo e(route('checklists.return',$checklist)); ?>" class="mt-4 space-y-3"><?php echo csrf_field(); ?><input type="hidden" name="_fiscal_year_id" value="<?php echo e($workingFiscalYear?->id); ?>"><label class="block text-sm">Return type<select name="return_type" class="block w-full border rounded-lg p-2"><option value="goods_and_invoice">Goods and invoice</option><option value="invoice">Invoice correction</option><option value="service_correction">Service correction</option></select></label><label class="block text-sm">Reason and required correction<textarea name="reason" required maxlength="3000" rows="3" class="block w-full border rounded-lg p-2"></textarea></label><p class="text-xs text-gray-500">The vendor will be notified. Unpaid, unauthorised payment records for this invoice will be cancelled.</p><button class="btn-danger">Return to vendor</button></form></details><?php endif; ?>
<?php endif; ?>
<div class="max-w-5xl space-y-5">
    <?php if(session('success')): ?><div class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800"><?php echo e(session('success')); ?></div><?php endif; ?>
    <?php if($errors->any()): ?><div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><ul class="list-disc list-inside"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
    <div class="bg-[#0B1E3D] rounded-xl p-6 text-white flex flex-wrap justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-wide text-teal-300">Vendor bill control</p><h1 class="mt-1 font-mono text-2xl font-bold"><?php echo e($checklist->purchaseOrder->po_number); ?></h1><p class="mt-2 text-sm text-slate-300">Bill <?php echo e($checklist->vendorBill->bill_number); ?> · <?php echo e($checklist->vendor->name); ?></p></div><div class="text-right"><span class="inline-flex rounded-full bg-white/15 px-3 py-1 text-sm font-semibold"><?php echo e($checklist->statusLabel()); ?></span><p class="mt-3 text-lg font-bold">Rs <?php echo e(number_format($checklist->vendorBill->amount, 2)); ?></p></div></div>

    <div class="grid gap-5 sm:grid-cols-3"><div class="rounded-xl border border-gray-200 bg-white p-5"><p class="text-xs uppercase font-semibold text-gray-400">Bill date</p><p class="mt-2 font-medium text-gray-800"><?php echo e($checklist->vendorBill->bill_date?->format('d M Y')); ?></p></div><div class="rounded-xl border border-gray-200 bg-white p-5"><p class="text-xs uppercase font-semibold text-gray-400">Vendor bill</p><p class="mt-2 font-medium text-gray-800"><?php echo e($checklist->vendorBill->original_name); ?></p><a href="<?php echo e(route('purchase-orders.vendor-bills.download', [$checklist->purchaseOrder, $checklist->vendorBill])); ?>" class="mt-2 inline-block text-sm font-semibold text-teal-700">Download bill →</a></div><div class="rounded-xl border border-gray-200 bg-white p-5"><p class="text-xs uppercase font-semibold text-gray-400">PO total</p><p class="mt-2 font-medium text-gray-800">Rs <?php echo e(number_format($checklist->purchaseOrder->total_amount, 2)); ?></p><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('purchase_orders.view')): ?>
<a href="<?php echo e(route('purchase-orders.show', $checklist->purchaseOrder)); ?>" class="mt-2 inline-block text-sm font-semibold text-teal-700">View purchase order →</a>
<?php endif; ?></div></div>

    <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->denies('checklists.complete')): ?>
    <section class="kcard p-6"><h2 class="font-semibold mb-3">Control questions</h2><?php $__currentLoopData = $checklist->requiredChecks(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><p class="text-sm py-2 border-b"><?php echo e($checklist->answerChecked($key) ? '✓' : '○'); ?> <?php echo e($label); ?></p><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><p class="mt-3 text-sm text-gray-600"><?php echo e($checklist->control_comments); ?></p></section>
    <?php endif; ?>
    <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('checklists.complete')): ?>
<form method="POST" action="<?php echo e(route('checklists.update', $checklist)); ?>" class="rounded-xl border border-gray-200 bg-white overflow-hidden"><?php echo csrf_field(); ?>
<input type="hidden" name="_fiscal_year_id" value="<?php echo e($workingFiscalYear?->id); ?>"> <?php echo method_field('PUT'); ?>
        <div class="border-b border-gray-100 px-6 py-5"><h2 class="font-semibold text-gray-800">Control questions</h2><p class="mt-1 text-sm text-gray-500">Select the fulfilment type, then tick every required control. Questions marked * are required before the bill can go to Accounts.</p></div>
        <div class="p-6">
            <fieldset <?php if($checklist->isSentToAccounts() || $checklist->status==='returned'): echo 'disabled'; endif; ?>><div class="mb-5"><p class="mb-2 text-sm font-medium text-gray-700">Fulfilment type</p><label class="mr-5 inline-flex items-center gap-2 text-sm"><input type="radio" name="fulfillment_type" value="goods" <?php if(old('fulfillment_type', $checklist->fulfillment_type) === 'goods'): echo 'checked'; endif; ?>> Goods</label><label class="inline-flex items-center gap-2 text-sm"><input type="radio" name="fulfillment_type" value="service" <?php if(old('fulfillment_type', $checklist->fulfillment_type) === 'service'): echo 'checked'; endif; ?>> Service</label></div>
            <div x-data="{ type: <?php echo \Illuminate\Support\Js::from(old('fulfillment_type',$checklist->fulfillment_type))->toHtml() ?>, sets: <?php echo \Illuminate\Support\Js::from($questionSets)->toHtml() ?>, answers: <?php echo \Illuminate\Support\Js::from(old('answers',$initialAnswers))->toHtml() ?> }" @change.window="if ($event.target.name === 'fulfillment_type') { type=$event.target.value; answers={}; }" class="space-y-3">
                <template x-for="(question,key) in sets[type]" :key="type+key"><label class="flex gap-3 border rounded-lg px-4 py-3 text-sm"><input type="checkbox" :name="'answers['+key+']'" value="1" x-model="answers[key]"><span x-text="question.label+(question.required?' *':'')"></span></label></template>
                <p x-show="Object.keys(sets[type]).length===0" class="text-sm text-amber-800">No controls configured. Ask an administrator to add questions.</p>
            </div>
            <label class="mt-5 block text-sm font-medium text-gray-700">Control comments<textarea name="control_comments" rows="3" class="mt-1.5 w-full rounded-lg border-gray-300 text-sm focus:border-teal-500 focus:ring-teal-500"><?php echo e(old('control_comments', $checklist->control_comments)); ?></textarea></label>
            <?php if(! $checklist->isSentToAccounts()): ?><button class="mt-5 rounded-lg bg-[#0B1E3D] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#162A45]">Save checklist</button><?php endif; ?></fieldset>
        </div>
    </form>
<?php endif; ?>

    <?php if($checklist->isReadyForAccounts()): ?><div class="rounded-xl border border-teal-200 bg-teal-50 p-6"><h2 class="font-semibold text-teal-900">Ready for Accounts</h2><p class="mt-1 text-sm text-teal-800">All controls have been completed by <?php echo e($checklist->completedBy?->name); ?>. Add an optional handover note and formally send this bill for payment processing.</p><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('checklists.complete')): ?>
<form method="POST" action="<?php echo e(route('checklists.send-to-accounts', $checklist)); ?>" class="mt-4 flex flex-col gap-3 sm:flex-row"><?php echo csrf_field(); ?>
<input type="hidden" name="_fiscal_year_id" value="<?php echo e($workingFiscalYear?->id); ?>"><input name="accounts_comment" placeholder="Optional Accounts handover comment" class="flex-1 rounded-lg border-teal-300 text-sm focus:border-teal-500 focus:ring-teal-500"><button class="rounded-lg bg-teal-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-teal-700">Send to Accounts for Payment</button></form>
<?php endif; ?></div><?php endif; ?>
    <?php if($checklist->isSentToAccounts() && ! $checklist->checklistPayment): ?><div class="rounded-xl border border-amber-200 bg-amber-50 p-6"><h2 class="font-semibold text-amber-900">Payment record needs recovery</h2><p class="mt-1 text-sm text-amber-800">This checklist was sent before its payment record could be created. Recover it once to create the missing payable record without duplicating the bill.</p><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('checklists.complete')): ?>
<form method="POST" action="<?php echo e(route('checklists.send-to-accounts', $checklist)); ?>" class="mt-4"><?php echo csrf_field(); ?>
<input type="hidden" name="_fiscal_year_id" value="<?php echo e($workingFiscalYear?->id); ?>"><button class="rounded-lg bg-amber-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-amber-700">Recover payment record</button></form>
<?php endif; ?></div><?php elseif($checklist->isSentToAccounts()): ?><div class="rounded-xl border border-green-200 bg-green-50 p-6"><h2 class="font-semibold text-green-900">Sent to Accounts for payment</h2><p class="mt-1 text-sm text-green-800">Sent by <?php echo e($checklist->accountsSentBy?->name); ?> on <?php echo e($checklist->accounts_sent_at?->format('d M Y H:i')); ?>. A payment record has been created in the Payments module for Finance to process.<?php if($checklist->accounts_comment): ?> Note: <?php echo e($checklist->accounts_comment); ?><?php endif; ?></p></div><?php endif; ?>

    <div class="rounded-xl border border-gray-200 bg-white overflow-hidden"><div class="px-6 py-4 border-b border-gray-100 flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-gray-800">PO approval record</h2><p class="mt-1 text-sm text-gray-500">Included in the printable Accounts support pack.</p></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('checklists.view')): ?>
<a href="<?php echo e(route('checklists.pdf', $checklist)); ?>" class="rounded-lg bg-gray-100 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-200">Download PDF support pack</a>
<?php endif; ?></div><div class="divide-y divide-gray-100"><?php $__empty_1 = true; $__currentLoopData = $checklist->purchaseOrder->approvalActions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $action): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="px-6 py-3 text-sm"><span class="font-semibold text-gray-800"><?php echo e($action->actor?->name); ?></span> · <?php echo e(ucfirst(str_replace('_', ' ', $action->decision))); ?> <span class="text-xs text-gray-400"><?php echo e($action->acted_at?->format('d M Y H:i')); ?></span><?php if($action->note): ?><p class="mt-1 text-xs text-gray-500"><?php echo e($action->note); ?></p><?php endif; ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="px-6 py-5 text-sm text-gray-500">No approval actions recorded.</div><?php endif; ?></div></div>
    <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('checklists.view')): ?>
<a href="<?php echo e(route('checklists.index')); ?>" class="inline-block text-sm text-gray-500 hover:text-gray-700">← Back to Checklists</a>
<?php endif; ?>
</div>

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ashbinkumarchamrel/Downloads/kathford-process/resources/views/checklists/show.blade.php ENDPATH**/ ?>