<div class="border rounded-lg p-4 mb-3 grid grid-cols-1 md:grid-cols-3 gap-3">
<div class="md:col-span-2"><label><?php echo e($type==='plan'?'Activity':'Title'); ?> *</label><input name="items[<?php echo e($i); ?>][title]" required value="<?php echo e($row['title']??''); ?>"></div>
<div><label>Owner</label><select name="items[<?php echo e($i); ?>][owner_id]"><option value="">Document creator</option><?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $u): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($u->id); ?>" <?php if(($row['owner_id']??'')===$u->id): echo 'selected'; endif; ?>><?php echo e($u->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
<div><label>Due date (AD)</label><input type="date" name="items[<?php echo e($i); ?>][due_on]" value="<?php echo e($row['due_on']??''); ?>"></div>
<div class="md:col-span-2"><label>Definition of Done</label><textarea name="items[<?php echo e($i); ?>][definition_of_done]" rows="2"><?php echo e($row['definition_of_done']??''); ?></textarea></div>
<?php if(in_array($type,['strategy','goals'])): ?>
<div><label>Metric / unit</label><input name="items[<?php echo e($i); ?>][metric]" placeholder="e.g. Canvas adoption (%)" value="<?php echo e($row['metric']??''); ?>"></div><div><label>Baseline</label><input type="number" step="0.01" min="0" name="items[<?php echo e($i); ?>][baseline]" value="<?php echo e($row['baseline']??''); ?>"></div><div><label>Target</label><input type="number" step="0.01" min="0" name="items[<?php echo e($i); ?>][target]" value="<?php echo e($row['target']??''); ?>"></div>
<?php endif; ?>
<?php if($type==='plan'): ?>
<div><label>Programme</label><input name="items[<?php echo e($i); ?>][programme]" value="<?php echo e($row['programme']??''); ?>"></div><div><label>Batch</label><input name="items[<?php echo e($i); ?>][batch]" value="<?php echo e($row['batch']??''); ?>"></div>
<div><label>Support department</label><select name="items[<?php echo e($i); ?>][support_department_id]"><option value="">No support required</option><?php $__currentLoopData = $supportDepartments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($d->id); ?>" <?php if(($row['support_department_id']??'')===$d->id): echo 'selected'; endif; ?>><?php echo e($d->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
<div><label><input type="checkbox" name="items[<?php echo e($i); ?>][requires_budget]" value="1" <?php if($row['requires_budget']??false): echo 'checked'; endif; ?>> Requires budget</label></div>
<?php endif; ?>
<?php if($type==='budget'): ?>
<div class="md:col-span-2"><label>Approved activity *</label><select required name="items[<?php echo e($i); ?>][source_id]"><option value="">Select approved activity</option><?php $__currentLoopData = $parents->where('type','plan'); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $plan): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $__currentLoopData = $plan->items->where('requires_budget',true); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $activity): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($activity->id); ?>" <?php if(($row['source_id']??'')===$activity->id): echo 'selected'; endif; ?>><?php echo e($plan->title); ?> · <?php echo e($activity->title); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div><label>Allocation (NPR) *</label><input required type="number" min="0.01" step="0.01" name="items[<?php echo e($i); ?>][amount]" value="<?php echo e($row['amount']??''); ?>"></div>
<?php endif; ?>
<div class="md:col-span-3"><label>Description / logistics / assumptions</label><textarea name="items[<?php echo e($i); ?>][description]" rows="2"><?php echo e($row['description']??''); ?></textarea></div><button type="button" class="text-red-600 text-sm text-left" onclick="this.parentElement.remove()">Remove item</button>
</div>
<?php /**PATH /Users/ashbinkumarchamrel/Downloads/kathford-process/resources/views/planning/item-fields.blade.php ENDPATH**/ ?>