<?php $__env->startSection('planning-content'); ?>
<div class="kcard p-5 space-y-3"><div class="flex justify-between gap-3"><h2 class="font-semibold text-lg"><?php echo e($document->title); ?></h2><span><?php echo e(ucwords(str_replace('_',' ',$document->status))); ?></span></div><p class="text-sm text-gray-500"><?php echo e($document->department?->name ?? 'College'); ?> · <?php echo e($document->period?->name); ?> · Revision <?php echo e($document->revision); ?></p><p class="whitespace-pre-line"><?php echo e($document->description); ?></p>
<?php if($document->parent): ?><p class="text-sm">Linked to: <a href="<?php echo e(route('planning.show',$document->parent)); ?>"><?php echo e($document->parent->title); ?></a></p><?php endif; ?>
<?php if(in_array($document->status,['draft','returned'])): ?><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('planning.'.$document->type.'_create')): ?><a href="<?php echo e(route('planning.edit',$document)); ?>">Edit draft</a><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('planning.'.$document->type.'_submit')): ?><form method="POST" action="<?php echo e(route('planning.action',$document)); ?>"><?php echo csrf_field(); ?><input type="hidden" name="version" value="<?php echo e($document->version); ?>"><button class="btn-primary" name="action" value="submit">Submit for approval</button></form><?php endif; ?> <?php endif; ?>
<?php if(in_array($document->status,['pending_verification','pending_approval'])): ?><p class="text-sm">Awaiting <?php echo e($document->step()['name']??''); ?></p><?php if(($document->step()['user_id']??null)===auth()->id()): ?><form method="POST" action="<?php echo e(route('planning.action',$document)); ?>" class="space-y-3"><?php echo csrf_field(); ?><input type="hidden" name="version" value="<?php echo e($document->version); ?>"><textarea name="note" placeholder="Decision note (required when returning or rejecting)"></textarea><div class="flex gap-3"><button name="action" value="accept" class="btn-primary"><?php echo e($document->status==='pending_verification'?'Verify':'Approve'); ?></button><button name="action" value="return" class="btn-secondary">Return</button><button name="action" value="reject" class="text-red-600">Reject</button></div></form><?php endif; ?> <?php endif; ?>
</div>
<div class="kcard overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Item</th><th>Owner / due date</th><th><?php echo e($document->type==='budget'?'Allocation':'Target / budget'); ?></th><th>Definition of Done</th></tr></thead><tbody><?php $__currentLoopData = $document->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="max-w-md"><?php echo e($item->title); ?><div class="text-xs text-gray-500 whitespace-pre-line"><?php echo e($item->description); ?></div></td><td><?php echo e($item->owner?->name ?? $document->creator?->name); ?><div class="text-xs"><?php echo e($item->due_on); ?></div></td><td><?php if($document->type==='budget'): ?>Rs <?php echo e(number_format($item->amount,2)); ?><?php if(isset($publications[$item->id])): ?><div class="text-xs text-teal-700">Published to Department Budgets</div><?php endif; ?> <?php else: ?> <?php echo e($item->target); ?> <?php echo e($item->metric); ?> <?php if($item->requires_budget): ?><div class="text-xs">Budget required</div><?php endif; ?> <?php endif; ?></td><td class="max-w-sm whitespace-pre-line"><?php echo e($item->definition_of_done); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div>
<details class="kcard p-4"><summary>Approval history</summary><?php $__empty_1 = true; $__currentLoopData = $document->decisions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $decision): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><p class="text-sm py-2"><?php echo e($decision->created_at); ?> · <?php echo e($decision->actor?->name); ?> · <?php echo e(ucfirst($decision->decision)); ?><span class="block text-gray-500"><?php echo e($decision->note); ?></span></p><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-2 text-sm">No decisions yet.</p><?php endif; ?></details>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('planning.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ashbinkumarchamrel/Downloads/kathford-process/resources/views/planning/show.blade.php ENDPATH**/ ?>