@extends('layouts.vendor-portal')
@section('title', 'Supplier workspace')
@section('content')
@foreach(\App\Models\ProcurementReturn::where('vendor_id',$vendor->id)->whereHas('checklist')->with('checklist.vendorBill')->latest()->get() as $return)
<section class="mb-4 rounded-xl border border-red-200 bg-red-50 p-5"><h2 class="font-semibold text-red-800">Invoice returned · {{ $return->checklist->vendorBill->bill_number }}</h2><p class="mt-2 text-sm text-red-900">{{ $return->reason }}</p><p class="mt-2 text-xs text-red-700">{{ $return->created_at->format('d M Y H:i') }} · Please submit corrected goods/invoice through the purchase order.</p></section>
@endforeach
<h1 class="text-xl font-semibold text-slate-900">Welcome back, {{ $vendor->name }}</h1>
<section class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><a href="{{ route('vendor.portal.orders.index', ['filter' => 'open']) }}" class="rounded-xl border border-amber-200 bg-white p-5 transition hover:border-amber-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Purchase orders</p><p class="mt-3 text-3xl font-bold text-slate-900">{{ $poSummary['pending'] }}</p><p class="mt-1 text-xs text-slate-500">Open orders needing an invoice</p></a><a href="{{ route('vendor.portal.quotes.index', ['filter' => 'action']) }}" class="rounded-xl border border-amber-200 bg-white p-5 transition hover:border-amber-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Quotation requests</p><p class="mt-3 text-3xl font-bold text-slate-900">{{ $summary['action_required'] }}</p><p class="mt-1 text-xs text-slate-500">Quotes or negotiations requiring action</p></a><a href="{{ route('vendor.portal.payments.index') }}" class="rounded-xl border border-blue-200 bg-white p-5 transition hover:border-blue-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Payments</p><p class="mt-3 text-3xl font-bold text-slate-900">{{ $payments->count() }}</p><p class="mt-1 text-xs text-slate-500">Scheduled and authorised updates</p></a><a href="{{ route('vendor.portal.statement') }}" class="rounded-xl border border-teal-200 bg-white p-5 transition hover:border-teal-400 hover:shadow-sm"><p class="text-sm font-semibold text-slate-700">Account statement</p><p class="mt-3 text-lg font-bold text-teal-800">View ledger →</p><p class="mt-1 text-xs text-slate-500">Invoices, settlements, and balance</p></a></section>
@if($actionRequired->isNotEmpty())<section class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-5"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold text-slate-900">Needs attention</h2><p class="mt-1 text-sm text-slate-600">You have {{ $actionRequired->count() }} quotation request{{ $actionRequired->count() === 1 ? '' : 's' }} to review.</p></div><a href="{{ route('vendor.portal.quotes.index', ['filter' => 'action']) }}" class="rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-teal-700">Review requests</a></div></section>@endif
@endsection
