<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('planning_periods',function(Blueprint $t){$t->uuid('id')->primary();$t->string('name');$t->string('academic_year');$t->string('programme')->nullable();$t->string('batch')->nullable();$t->date('starts_on');$t->date('ends_on');$t->timestamps();});
  Schema::create('planning_documents',function(Blueprint $t){$t->uuid('id')->primary();$t->string('type',20)->index();$t->string('title');$t->uuid('department_id')->nullable()->index();$t->uuid('created_by');$t->uuid('period_id')->nullable();$t->uuid('parent_id')->nullable();$t->uuid('previous_id')->nullable();$t->unsignedInteger('revision')->default(1);$t->uuid('approval_chain_id')->nullable();$t->string('status',30)->default('draft')->index();$t->unsignedInteger('version')->default(1);$t->unsignedBigInteger('fiscal_year_id')->nullable();$t->text('description')->nullable();$t->json('steps')->nullable();$t->unsignedInteger('step_index')->default(0);$t->timestamp('approved_at')->nullable();$t->timestamps();$t->foreign('parent_id')->references('id')->on('planning_documents');$t->foreign('period_id')->references('id')->on('planning_periods');});
  Schema::create('planning_items',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('document_id')->index();$t->uuid('source_id')->nullable();$t->string('title');$t->text('description')->nullable();$t->uuid('owner_id')->nullable();$t->date('due_on')->nullable();$t->text('definition_of_done')->nullable();$t->string('metric')->nullable();$t->decimal('baseline',14,2)->nullable();$t->decimal('target',14,2)->nullable();$t->decimal('actual',14,2)->nullable();$t->boolean('requires_budget')->default(false);$t->decimal('amount',14,2)->default(0);$t->uuid('support_department_id')->nullable();$t->string('programme')->nullable();$t->string('batch')->nullable();$t->string('frequency')->default('once');$t->timestamps();$t->foreign('document_id')->references('id')->on('planning_documents');});
  Schema::create('planning_decisions',function(Blueprint $t){$t->id();$t->uuid('document_id')->index();$t->uuid('actor_id');$t->string('decision');$t->text('note')->nullable();$t->timestamps();});
  Schema::create('planning_budget_publications',function(Blueprint $t){$t->id();$t->uuid('item_id')->unique();$t->uuid('budget_id')->unique();$t->timestamps();});
  Schema::create('planning_support_requests',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('item_id')->unique();$t->uuid('department_id')->index();$t->string('status')->default('requested');$t->text('response')->nullable();$t->timestamps();});
  Schema::create('planning_sprints',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('department_id');$t->string('name');$t->text('goal')->nullable();$t->date('starts_on');$t->date('ends_on');$t->string('status')->default('planned');$t->timestamps();});
  Schema::create('planning_tasks',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('item_id')->nullable()->unique();$t->uuid('department_id')->nullable()->index();$t->uuid('created_by');$t->uuid('assignee_id');$t->uuid('reviewer_id')->nullable();$t->uuid('sprint_id')->nullable();$t->uuid('parent_id')->nullable();$t->boolean('is_private')->default(false);$t->string('title');$t->text('description')->nullable();$t->text('definition_of_done')->nullable();$t->text('evidence')->nullable();$t->text('blocked_reason')->nullable();$t->string('status')->default('todo');$t->string('priority')->default('normal');$t->date('due_on')->nullable();$t->unsignedInteger('version')->default(1);$t->timestamps();});
  Schema::create('planning_task_events',function(Blueprint $t){$t->id();$t->uuid('task_id')->index();$t->uuid('actor_id');$t->string('action');$t->text('note')->nullable();$t->timestamps();});
  foreach(\App\Services\Planning\Access::permissions() as $key=>$label) \App\Models\Permission::firstOrCreate(['key'=>$key],['label'=>$label,'module'=>'planning','sort_order'=>100]);
 }
 public function down(): void {foreach(['task_events','tasks','sprints','support_requests','budget_publications','decisions','items','documents','periods'] as $table) Schema::dropIfExists('planning_'.$table);}
};
