@extends('layouts.app')
@section('title', 'Procurement Checklists')
@section('page-title', 'Procurement Checklists')

@section('content')
<div class="mx-auto max-w-[1600px] space-y-3">
    
    <section class="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><form method="GET" class="flex flex-wrap items-end gap-3"><input type="hidden" name="status" value="{{ request('status') }}"><label class="block flex-1 min-w-[200px]"><span class="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-gray-500">Find a checklist</span><div class="relative"><svg class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><circle cx="11" cy="11" r="7"/><path stroke-linecap="round" d="m20 20-4-4"/></svg><input type="search" name="search" value="{{ request('search') }}" placeholder="PO number, bill or vendor" class="w-full rounded-lg border border-gray-300 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100"></div></label><button class="btn-primary h-[42px]">Apply filters</button></form><div class="mt-4 flex flex-wrap gap-1.5 border-t border-gray-100 pt-3">@can('checklists.view')
<a href="{{ route('checklists.index', request()->except('status','page')) }}" class="rounded-lg px-3 py-2 text-xs font-semibold {{ !request('status') ? 'bg-[#0B1E3D] text-white' : 'text-gray-600 hover:bg-gray-100' }}">All checklists</a>
@endcan
@can('checklists.view')
<a href="{{ route('checklists.index', array_merge(request()->except('status','page'), ['status' => 'pending_controls'])) }}" class="rounded-lg px-3 py-2 text-xs font-semibold {{ request('status') === 'pending_controls' ? 'bg-[#0B1E3D] text-white' : 'text-gray-600 hover:bg-gray-100' }}">Pending controls</a>
@endcan
@can('checklists.view')
<a href="{{ route('checklists.index', array_merge(request()->except('status','page'), ['status' => 'ready_for_accounts'])) }}" class="rounded-lg px-3 py-2 text-xs font-semibold {{ request('status') === 'ready_for_accounts' ? 'bg-[#0B1E3D] text-white' : 'text-gray-600 hover:bg-gray-100' }}">Ready for Accounts</a>
@endcan
@can('checklists.view')
<a href="{{ route('checklists.index', array_merge(request()->except('status','page'), ['status' => 'sent_to_accounts'])) }}" class="rounded-lg px-3 py-2 text-xs font-semibold {{ request('status') === 'sent_to_accounts' ? 'bg-[#0B1E3D] text-white' : 'text-gray-600 hover:bg-gray-100' }}">Sent to Accounts</a>
@endcan</div></section>
    <div class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-gray-100 px-3 py-2"><div><h2 class="font-semibold text-gray-800">Vendor bills awaiting controls</h2><p class="mt-1 text-sm text-gray-500">{{ $checklists->total() }} bill{{ $checklists->total() === 1 ? '' : 's' }} in this view.</p></div></div><x-super-admin-bulk-delete module="checklists" /><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr>@if(auth()->user()->isSuperAdmin())<th class="w-10 px-3 py-3"><input type="checkbox" aria-label="Select all checklists" data-bulk-delete-toggle="checklists"></th>@endif<th class="px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase">PO / Bill</th><th class="px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase">Vendor</th><th class="px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase">Type</th><th class="px-3 py-2 text-right text-xs font-semibold text-gray-500 uppercase">Amount</th><th class="px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase">Status</th><th class="px-3 py-2"></th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($checklists as $checklist)<tr class="hover:bg-gray-50">@if(auth()->user()->isSuperAdmin())<td class="px-3 py-3"><input type="checkbox" value="{{ $checklist->id }}" aria-label="Select checklist" data-bulk-delete-record="checklists"></td>@endif<td class="px-3 py-2"><p class="font-mono text-xs font-bold text-gray-700">{{ $checklist->purchaseOrder?->po_number }}</p><p class="mt-1 text-sm text-gray-700">Bill: {{ $checklist->vendorBill?->bill_number }}</p></td><td class="px-3 py-2 text-gray-700">{{ $checklist->vendor?->name }}</td><td class="px-3 py-2 capitalize text-gray-600">{{ $checklist->fulfillment_type }}</td><td class="px-3 py-2 text-right font-mono text-gray-800">Rs {{ number_format($checklist->vendorBill?->amount ?? 0, 2) }}</td><td class="px-3 py-2"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $checklist->status === 'sent_to_accounts' ? 'bg-green-100 text-green-800' : ($checklist->status === 'ready_for_accounts' ? 'bg-teal-100 text-teal-800' : 'bg-amber-100 text-amber-800') }}">{{ $checklist->statusLabel() }}</span></td><td class="px-3 py-2 text-right">@can('checklists.view')
<a href="{{ route('checklists.show', $checklist) }}" class="font-semibold text-teal-700 hover:text-teal-800">Review →</a>
@endcan</td></tr>@empty<tr><td colspan="{{ auth()->user()->isSuperAdmin() ? 7 : 6 }}" class="px-5 py-14 text-center text-gray-400">No vendor bill checklists found.</td></tr>@endforelse</tbody></table></div>@if($checklists->hasPages())<div class="px-3 py-2 border-t border-gray-100">{{ $checklists->links() }}</div>@endif</div>
</div>
@endsection
