<!DOCTYPE html>
<html><head><meta charset="UTF-8"><style>body{font-family:DejaVu Sans,sans-serif;color:#182233;font-size:10px}.header{background:#0B1E3D;color:white;padding:18px;display:table;width:100%}.header-logo,.header-copy{display:table-cell;vertical-align:middle}.header-logo{width:160px}.header h1{margin:4px 0;font-size:20px}.logo{width:145px;height:72px;padding:5px;background:#fff;object-fit:contain;object-position:center;border-radius:4px}.muted{color:#667085}.section{margin-top:16px;border:1px solid #d9e0e8;padding:12px}.section h2{font-size:13px;margin:0 0 8px}.grid{width:100%;border-collapse:collapse}.grid td,.grid th{border:1px solid #d9e0e8;padding:7px;text-align:left}.grid th{background:#f4f6f8;font-size:9px;text-transform:uppercase}.ok{color:#087443;font-weight:bold}.no{color:#b42318;font-weight:bold}.status{background:#e8f7f2;color:#075c4c;padding:4px 8px;font-weight:bold}.note{white-space:pre-line}.footer{margin-top:18px;color:#667085;font-size:8px}</style></head><body>
<div class="header"><div class="header-logo">@if($companyLogoPath)<img class="logo" src="{{ $companyLogoPath }}" alt="Organisation logo">@endif</div><div class="header-copy"><div style="font-size:10px;color:#9fe5dc">ACCOUNTS SUPPORT PACK</div><h1>Procurement Checklist: {{ $checklist->purchaseOrder->po_number }}</h1><div>Vendor bill {{ $checklist->vendorBill->bill_number }} · Generated {{ now()->format('d M Y H:i') }}</div></div></div>
<div class="section"><table width="100%"><tr><td width="50%"><strong>Vendor</strong><br>{{ $checklist->vendor->name }}<br>{{ $checklist->vendor->address }}</td><td width="25%"><strong>Bill Date</strong><br>{{ $checklist->vendorBill->bill_date?->format('d M Y') }}<br><br><strong>Bill Amount</strong><br>Rs {{ number_format($checklist->vendorBill->amount, 2) }}</td><td width="25%"><strong>PO Total</strong><br>Rs {{ number_format($checklist->purchaseOrder->total_amount, 2) }}<br><br><strong>Checklist status</strong><br><span class="status">{{ $checklist->statusLabel() }}</span></td></tr></table></div>
<div class="section"><h2>Purchase Order Items</h2><table class="grid" width="100%"><thead><tr><th>Description</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>@foreach($checklist->purchaseOrder->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->unit }}</td><td style="text-align:right">{{ $item->quantity }}</td><td style="text-align:right">Rs {{ number_format($item->unit_rate,2) }}</td><td style="text-align:right">Rs {{ number_format($item->total,2) }}</td></tr>@endforeach</tbody></table></div>
@php($quote = $checklist->purchaseOrder->rfqQuote)
@if($quote)
<div class="section"><h2>Accepted Vendor Quotation</h2><table width="100%"><tr><td width="35%"><strong>RFQ reference</strong><br>{{ $quote->rfq?->rfq_number ?? '—' }}<br>{{ $quote->rfq?->title }}</td><td width="30%"><strong>Quoted vendor</strong><br>{{ $quote->vendor?->name }}<br><br><strong>Quote submitted</strong><br>{{ $quote->submitted_at?->format('d M Y H:i') ?? '—' }}</td><td width="35%"><strong>Quoted amount</strong><br>Rs {{ number_format($quote->total_quoted, 2) }}<br><strong>Tax / Grand total</strong><br>Rs {{ number_format($quote->tax_amount, 2) }} / Rs {{ number_format($quote->grand_total, 2) }}</td></tr></table><p><strong>Delivery timeline:</strong> {{ $quote->delivery_timeline ?: '—' }} &nbsp;&nbsp; <strong>Payment terms:</strong> {{ $quote->payment_terms ?: '—' }}</p>@if($quote->notes)<p><strong>Quotation notes:</strong> {{ $quote->notes }}</p>@endif<table class="grid" width="100%"><thead><tr><th>Quoted item</th><th>Unit</th><th>Qty</th><th>Unit rate</th><th>Line total</th></tr></thead><tbody>@foreach($quote->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->unit }}</td><td style="text-align:right">{{ $item->quantity }}</td><td style="text-align:right">Rs {{ number_format($item->unit_rate, 2) }}</td><td style="text-align:right">Rs {{ number_format($item->total, 2) }}</td></tr>@endforeach</tbody></table></div>
@else
<div class="section"><h2>Quotation Details</h2><p>This is a standalone purchase order; no RFQ quotation was used.</p></div>
@endif
@php($activityForm = $quote?->rfq?->activityForm)
@if($activityForm)
<div class="section"><h2>Activity Form and Approval Details</h2><table width="100%"><tr><td width="35%"><strong>Activity Form</strong><br>{{ $activityForm->form_number }}<br>{{ $activityForm->activity_name }}</td><td width="35%"><strong>Category / Department</strong><br>{{ $activityForm->category?->name ?? '—' }}<br>{{ $activityForm->department?->name ?? '—' }}</td><td width="30%"><strong>Status</strong><br>{{ $activityForm->statusLabel() }}<br><br><strong>Estimated amount</strong><br>Rs {{ number_format($activityForm->total_estimated_amount, 2) }}</td></tr></table><table class="grid" width="100%"><thead><tr><th>Approval action</th><th>By</th><th>Date / Time</th><th>Comment</th></tr></thead><tbody>@forelse($activityForm->approvalActions as $action)<tr><td>{{ ucfirst(str_replace('_', ' ', $action->decision)) }}</td><td>{{ $action->actor?->name }}</td><td>{{ $action->acted_at?->format('d M Y H:i') }}</td><td>{{ $action->note ?: '—' }}</td></tr>@empty<tr><td colspan="4">No Activity Form approval actions recorded.</td></tr>@endforelse</tbody></table></div>
@else
<div class="section"><h2>Activity Form Approval Details</h2><p>No Activity Form is linked to this RFQ/PO.</p></div>
@endif
<div class="section"><h2>Control Checklist ({{ ucfirst($checklist->fulfillment_type) }})</h2><table class="grid" width="100%"><thead><tr><th>Control</th><th>Result</th></tr></thead><tbody>@foreach($checklist->requiredChecks() as $field => $label)<tr><td>{{ $label }}</td><td class="{{ $checklist->answerChecked($field) ? 'ok' : 'no' }}">{{ $checklist->answerChecked($field) ? 'Checked' : 'Not checked' }}</td></tr>@endforeach</tbody></table><p><strong>Control comments:</strong> <span class="note">{{ $checklist->control_comments ?: '—' }}</span></p><p><strong>Completed by:</strong> {{ $checklist->completedBy?->name ?? '—' }} {{ $checklist->completed_at ? 'on '.$checklist->completed_at->format('d M Y H:i') : '' }}</p><p><strong>Accounts handover:</strong> {{ $checklist->accountsSentBy?->name ?? 'Not yet sent' }} {{ $checklist->accounts_sent_at ? 'on '.$checklist->accounts_sent_at->format('d M Y H:i') : '' }}<br><strong>Accounts comments:</strong> {{ $checklist->accounts_comment ?: '—' }}</p></div>
<div class="section"><h2>Purchase Order Approval Details</h2><table class="grid" width="100%"><thead><tr><th>Action</th><th>By</th><th>Date / Time</th><th>Comment</th></tr></thead><tbody>@forelse($checklist->purchaseOrder->approvalActions as $action)<tr><td>{{ ucfirst(str_replace('_',' ',$action->decision)) }}</td><td>{{ $action->actor?->name }}</td><td>{{ $action->acted_at?->format('d M Y H:i') }}</td><td>{{ $action->note ?: '—' }}</td></tr>@empty<tr><td colspan="4">No approval actions recorded.</td></tr>@endforelse</tbody></table></div>
<div class="section"><h2>Checklist Process Log</h2><table class="grid" width="100%"><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Details</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr><td>{{ $log->logged_at?->format('d M Y H:i') }}</td><td>{{ $log->user_email ?: 'System / Vendor' }}</td><td>{{ ucfirst(str_replace('_',' ',str_replace('procurement_checklist.','',$log->action))) }}</td><td>{{ $log->new_values ? json_encode($log->new_values) : '—' }}</td></tr>@empty<tr><td colspan="4">No checklist process entries recorded.</td></tr>@endforelse</tbody></table></div>
<div class="footer">This document is a system-generated supporting record for Accounts filing. Vendor bill file: {{ $checklist->vendorBill->original_name }}</div>
</body></html>
