<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>@yield('title', 'Supplier workspace')</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{fontFamily:{sans:['Roboto','ui-sans-serif','system-ui','sans-serif']}}}</script><style>body{font-family:'Roboto',ui-sans-serif,system-ui,sans-serif;-webkit-font-smoothing:antialiased}</style><link rel="stylesheet" href="{{ asset('css/portal.css') }}">
</head>
@php
    $organisationName = \App\Models\Setting::get('company_name', 'Kathford International College');
    $organisationLogo = \App\Models\Setting::get('company_logo_path');
@endphp
<body class="min-h-screen bg-slate-50 text-slate-800">
<header class="border-b border-slate-200 bg-white"><div class="mx-auto max-w-7xl px-4 sm:px-6"><div class="flex items-center justify-between gap-4 py-3"><a href="{{ route('vendor.portal.dashboard') }}" class="flex min-w-0 items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-md bg-slate-900 text-sm font-bold text-white">@if($organisationLogo)<img src="{{ asset('storage/'.$organisationLogo) }}" alt="Organisation logo" class="h-full w-full bg-white object-contain p-0.5">@else KI @endif</span><span class="min-w-0"><span class="block truncate text-sm font-semibold text-slate-950">{{ $organisationName }}</span><span class="block text-xs font-medium text-slate-500">Supplier workspace · {{ $vendor->name }}</span></span></a><div class="flex items-center gap-1 text-sm"><a href="{{ route('vendor.portal.profile.edit') }}" class="rounded-lg px-2.5 py-2 font-medium text-slate-600 hover:bg-slate-50">Profile</a><form method="POST" action="{{ route('vendor.portal.logout') }}">@csrf<button class="rounded-lg px-2.5 py-2 font-medium text-slate-500 hover:bg-slate-50">Sign out</button></form></div></div><nav class="-mx-1 flex gap-1 overflow-x-auto pb-3 text-sm font-semibold"><a href="{{ route('vendor.portal.dashboard') }}" class="shrink-0 rounded-lg px-3 py-2 {{ request()->routeIs('vendor.portal.dashboard') ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100' }}">Overview</a><a href="{{ route('vendor.portal.orders.index') }}" class="shrink-0 rounded-lg px-3 py-2 {{ request()->routeIs('vendor.portal.orders.*') ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100' }}">Purchase orders</a><a href="{{ route('vendor.portal.quotes.index') }}" class="shrink-0 rounded-lg px-3 py-2 {{ request()->routeIs('vendor.portal.quotes.*') ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100' }}">Quotation requests</a><a href="{{ route('vendor.portal.payments.index') }}" class="shrink-0 rounded-lg px-3 py-2 {{ request()->routeIs('vendor.portal.payments.*') ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100' }}">Payments</a><a href="{{ route('vendor.portal.statement') }}" class="shrink-0 rounded-lg px-3 py-2 {{ request()->routeIs('vendor.portal.statement') ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100' }}">Account statement</a></nav></div></header>
<main class="mx-auto max-w-7xl px-4 py-7 sm:px-6">@if(session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('success') }}</div>@endif @yield('content')</main>
</body></html>
